### ISSUE TITLE
[MEG] disable the cache

### ISSUE THREAD

**Issue by chr-engwer** [brainstorm-tools/bst-duneuro#10]
At least for the high density meshes you should not use the MEG functional cache as it requires too much memory.

Add
```
[meg]
cache.enable = false
```
to your configuration.

**Comment by tmedani** [comment]
yes, 
I have added this to my testing dataset and it is still computing without apparent errors,
I will let you know, I guess the error related to the grid will appear since I'm using a similar model.

**Comment by tmedani** [comment]
This is working, 
we will add this option to the duneuro option from Brainstorm 
https://github.com/tmedani/brainstorm3/blob/adbeb3b64547a028e670038a3b06fd9bf2fa517e/toolbox/forward/bst_duneuro.m#L417
