### ISSUE TITLE
First row of gain matrix contains only zeros

### ISSUE THREAD

**Issue by ftadel** [brainstorm-tools/bst-duneuro#13]
See this discussion on the Brainstorm forum:
https://neuroimage.usc.edu/forums/t/zeros-in-duneuro-gain-matrix/24369

**Comment by tmedani** [comment]
Hi @ftadel 

My answer to this issue is on the forum
https://neuroimage.usc.edu/forums/t/zeros-in-duneuro-gain-matrix/24369/4?u=tmedani

A+
