### ISSUE TITLE
Errors with duneuro

### ISSUE THREAD

**Issue by tmedani** [brainstorm-tools/bst-duneuro#7]
Hi, 

Just to report the different errors that we may face in the next future. 

Here is one, using a high-density mesh and strat the computation for EEG, 
```
.......
.......
dipole_8332.density = sparse
dipole_8332.time = 0
dipole_8333.density = sparse
dipole_8333.time = 0
Dune reported error: Dune::Exception [findEntityImpl:/home/juan/bst-duneuro/src/duneuro/duneuro/common/edgehopping.hh:84]: coordinate is outside of the grid, or grid is not convex


***************************************************************************
** Error: Error during the DUNEuro computation, see logs in the command window.
***************************************************************************
```
I will check it, but it seems that the dipole 8333 is outside of the brain or it can be something else!

let's see 

A+

**Comment by tmedani** [comment]
Here is another error that appears in some case when we use high mesh densities with the MEG

```
DUNEURO> System call: "C:\Users\33649\.brainstorm\bst_duneuro\bin\bst_duneuro_meeg_win64.exe" "C:\Users\33649\.brainstorm\tmp\duneuro_minifile.mini"
DUNEURO> Error log:
degree = 1
element_type = tetrahedron
WARNING: You are using AMG without SuperLU! Please consider installing SuperLU, or set the usesuperlu flag to false to suppress this warning.
time = 0.0258972
time = 0.0399071
Unknown exception thrown!


***************************************************************************
** Error: Error during the DUNEuro computation, see logs in the command window.
*************************************************************************** 
```

**Comment by ftadel** [comment]
@tmedani You assigned me this task, but I'm not sure how I can help with this...

**Comment by tmedani** [comment]
Hi, @ftadel indeed, 

maybe you can't for the Cpp core code, but you have always good advice :) 

We will probably have feedbacks from users in the future that reports same errors, we will try to solve them here or ask the Dune/Duneuro team.

**Comment by tmedani** [comment]
Another error happening with the hexa mesh without the shift


CondFile =

    'C:\Users\33649\.brainstorm\tmp\conductivity_model.con'

DUNEURO> System call: "C:\Users\33649\.brainstorm\bst_duneuro\bin\bst_duneuro_meeg_win64.exe" "C:\Users\33649\.brainstorm\tmp\duneuro_minifile.mini"
DUNEURO> Error log:
UGGridParameterBlock: Parameter 'closure' not specified, using default: 'GREEN'.
UGGridParameterBlock: Parameter 'copies' not specified, using default: 'NO'.
UGGridParameterBlock: Parameter 'heapsize' not specified, using default: '500' MB.


***************************************************************************
** Error: Error during the DUNEuro computation, see logs in the command window.
***************************************************************************

**Comment by chr-engwer** [comment]
@tmedani I checked your hex-file error.

1. this is not a valid hex file. the numbering of your vertices is broken. Please adhere to the [vertex numbering scheme](https://www.dune-project.org/doxygen/master/group__GeometryReferenceElements.html) of DUNE.
1. it might be better to use the sub-entity center search instead of the normal projection, as you have a structured (voxel) mesh
1. instead of writing an unstructured grid file for a structured grid it would be more appropriate to go for the structured grid and the filter cells using `dune-subgrid`, like we do it for node shift meshes (where we also start with the voxel mesh).

... I'll check for an option to attach an image of the broken cube.

**Comment by chr-engwer** [comment]
Here you see the wrong setup. I assume you used the cycling numbering in the bottom and top plane?! DUNE uses a tensor-product numbering.
![wrong-cube](https://user-images.githubusercontent.com/14291470/93367125-642b8c80-f84c-11ea-92e8-75cbd5801fb1.png)

**Comment by juangpc** [comment]
Can I suggest to center development on the gitlab side? It was us who created this repo, but at this point, why don't we concentrate all DUNEuro related stuff there and keep here the issues directly related with the interaction with brainstorm.
Just asking.

**Comment by chr-engwer** [comment]
I have put this information here, as this is not a duneuro issue, but a matlab/bst issue. But feel free to move the issue to gitlab if you like.

**Comment by tmedani** [comment]
> Here you see the wrong setup. I assume you used the cycling numbering in the bottom and top plane?! DUNE uses a tensor-product numbering.
> ![wrong-cube](https://user-images.githubusercontent.com/14291470/93367125-642b8c80-f84c-11ea-92e8-75cbd5801fb1.png)

ok, I did not notice that, I'm using duneuro with the same mesh as for the SimBio. 


> Can I suggest to center development on the gitlab side? It was us who created this repo, but at this point, why don't we concentrate all DUNEuro related stuff there and keep here the issues directly related with the interaction with brainstorm.
> Just asking.

ok, @juangpc  I will move this issue the duneuro gitlab asap

**Comment by chr-engwer** [comment]
On Wed, Sep 16, 2020 at 03:12:08PM -0700, Takfarinas MEDANI wrote:
> > Here you see the wrong setup. I assume you used the cycling numbering in the bottom and top plane?! DUNE uses a tensor-product numbering.
> > ![wrong-cube](https://user-images.githubusercontent.com/14291470/93367125-642b8c80-f84c-11ea-92e8-75cbd5801fb1.png)
> 
> ok, I yre reading notice that, I have feeding duneuro with the same mesh as for the SimBio.

No, you wrote a dgf file, which is definitely not understood by SimBio. But I guess the code is copy-and-paste from the SimBio export.

> > Can I suggest to center development on the gitlab side? It was us who created this repo, but at this point, why don't we concentrate all DUNEuro related stuff there and keep here the issues directly related with the interaction with brainstorm.
> > Just asking.
> 
> ok, @juangpc  I will move this issue the duneuro gitlab asap

Please keep the issues where they belong. This is not a problem of the C++ code. It is something you need to fix in your matlab code.

Ciao
Christian

**Comment by chr-engwer** [comment]
I created new issues for those things that need to be fixed on the matlab side.

Please feel free to close this issue here...

**Comment by tmedani** [comment]
> On Wed, Sep 16, 2020 at 03:12:08PM -0700, Takfarinas MEDANI wrote: > Here you see the wrong setup. I assume you used the cycling numbering in the bottom and top plane?! DUNE uses a tensor-product numbering. > ![wrong-cube](https://user-images.githubusercontent.com/14291470/93367125-642b8c80-f84c-11ea-92e8-75cbd5801fb1.png) ok, I yre reading notice that, I have feeding duneuro with the same mesh as for the SimBio.
> No, you wrote a dgf file, which is definitely not understood by SimBio. But I guess the code is copy-and-paste from the SimBio export.

Yes, we are using the output mesh from the simbio (the version ft-simbio) and put it in the dfg file to feed Duneuro with it.
I will check what is the difference between these and try to fixe it.

**Comment by tmedani** [comment]
> > On Wed, Sep 16, 2020 at 03:12:08PM -0700, Takfarinas MEDANI wrote: > Here you see the wrong setup. I assume you used the cycling numbering in the bottom and top plane?! DUNE uses a tensor-product numbering. > ![wrong-cube](https://user-images.githubusercontent.com/14291470/93367125-642b8c80-f84c-11ea-92e8-75cbd5801fb1.png) ok, I yre reading notice that, I have feeding duneuro with the same mesh as for the SimBio.
> > No, you wrote a dgf file, which is definitely not understood by SimBio. But I guess the code is copy-and-paste from the SimBio export.
> 
> Yes, we are using the output mesh from the simbio (the version ft-simbio) and put it in the dfg file to feed Duneuro with it.
> I will check what is the difference between these and try to fixe it.

So, from what I understand, this can be fixed from the matlab side.
we need just to reorder the node numbering?

**Comment by juangpc** [comment]
This will be taken care of in https://github.com/brainstorm-tools/bst-duneuro/issues/8
Closing.

**Comment by dunjadudu** [comment]
I used a coregistered T1 and T2 to create a FEM mesh with SIMnibs ,and the segmentation seemed to be ok  but the FEM generated isn't aligned with the T1 in the database anymore so  I'm wondering if the problem is solved already ? 
What can I do ? I tried also brain2mesh but it gave me errors in the segmentation and in the creation of the surfaces.
![3D_es_output2](https://user-images.githubusercontent.com/83778018/117334085-e0391a00-ae99-11eb-91c4-1950949e4bbe.png)
Thank You for the support

**Comment by tmedani** [comment]
Hi @dunjadudu 

> I used a coregistered T1 and T2 to create a FEM mesh with SIMnibs ,and the segmentation seemed to be ok but the FEM generated isn't aligned with the T1 in the database anymore so I'm wondering if the problem is solved already ?
> What can I do ? I tried also brain2mesh but it gave me errors in the segmentation and in the creation of the surfaces.

Which Brainstorm version are you using? 
we have solved this issue a few months ago. 

Check also this discussion :
https://neuroimage.usc.edu/forums/t/headmodel-with-eeg-questions/27765

And let us know if you still have the problem.

**Comment by dunjadudu** [comment]
Hi @tmedani , I'm using 07 May 2021 version , on matlab R2021a , SIMnibs3-2 , working on windows . I did not move the electrodes for coregistration , the problem arise before , because there is no correspondence between segmented MRI (tissues) and MRI imported ( I used T1 and T2 for FEM modeling, with T2 resliced and coregistered correctly on T1 ). How can I avoid the shift ? T1 and T2 come from freesurfer processed images therefore , usually imported as FS folder

**Comment by tmedani** [comment]
> because there is no correspondence between segmented MRI (tissues) and MRI

Do you mean that you imported the T1 and T2 after getting the tissues?

The tissues are generated from the segmentation of T1 and T2, they should be in the same space? 

@ftadel do you have any idea about this issue, 
is there any change recently?

**Comment by dunjadudu** [comment]
Hi, I tried using only T1 for the segmentation , thus avoiding the problem with coregistration . The segmentation is now coregistered to the MRI, however the surfaces obtained from FEM are not coregistered with MRI ( I have again a shift). 
I don't see error messages during the implementation although I cannot display the FEM mesh . I tried also other options ( Fieldtrip FEM but it fails in surface reconstruction, Brain2mesh other errors ) but probably SimNIBS seems the most reliable from your discussions. Have you any idea how to solve a problem and what should I check? Thank You  for Your support! 
Dunja

**Comment by tmedani** [comment]
> Dunja

Hi, could you share your MRI or send it in private I will have a look at it. 
your MRI may have some missing information, but I can't guess what and why.

**Comment by tmedani** [comment]
I will close and move this issue from this thread since it's not related to DUNEURO.

**Comment by tmedani** [comment]
@dunjadudu 
please join the discussion in this [https://github.com/brainstorm-tools/brainstorm3/issues/413#issue-902911650)

**Comment by tmedani** [comment]
https://github.com/brainstorm-tools/brainstorm3/issues/413#issue-902911650
